version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-webserver:
    build:
      context: ./airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=9dgWANWc6U3VUHtbj8no1nKXkyPmGL1UZPm-O9Yra48=
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/airflow_logs:/opt/airflow/logs
    command: webserver

  airflow-scheduler:
    build:
      context: ./airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=9dgWANWc6U3VUHtbj8no1nKXkyPmGL1UZPm-O9Yra48=
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/airflow_logs:/opt/airflow/logs
    command: scheduler

  # scrapy:
  #   build:
  #     context: ./scrapy
  #   environment:
  #     - SCRAPY_SETTINGS_MODULE=myproject.settings
  #   volumes:
  #     - ./scrapy_project:/usr/src/app
  #   command: scrapy crawl myspider

volumes:
  postgres_db_data:
  airflow_logs:
