version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow-webserver:
    build:
      context: ./airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/airflow_logs:/opt/airflow/logs
      - ${HOST_AIRFLOW_PATH}:/host/airflow  # Use environment variable for the host path
    command: webserver

  airflow-scheduler:
    build:
      context: ./airflow
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/airflow_logs:/opt/airflow/logs
      - ${HOST_AIRFLOW_PATH}:/host/airflow  # Use environment variable for the host path
    command: scheduler

volumes:
  postgres_db_data:
  airflow_logs:
