name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build Docker image
      run: |
        cd airflow
        docker build -t gdw888/docker-images-hub:nba-statistic-tracker-airflow .
        cd ..

    - name: Push Docker image
      run: |
        docker push gdw888/docker-images-hub:nba-statistic-tracker-airflow

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Kubernetes (or other environment)
      run: |
        echo "Deployment steps go here"
        # Add your deployment script or commands here
