name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Airflow Docker image
      run: |
        cd airflow
        docker build -t gdw888/docker-images-hub:nba-statistic-tracker-airflow .
        cd ..

    - name: Push Airflow Docker image 
      run: |
        docker push gdw888/docker-images-hub:nba-statistic-tracker-airflow

    - name: Build scrapy Docker image
      run: |
        cd scrapy
        docker build -t gdw888/docker-images-hub:nba-statistic-tracker-scrapy .
        cd ..

    - name: Push scrapy Docker image 
      run: |
        docker push gdw888/docker-images-hub:nba-statistic-tracker-scrapy

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd scrapy
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd scrapy/nba_stats/nba_stats/spiders/tests
        pytest --junitxml=results.xml

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: scrapy/nba_stats/nba_stats/spiders/tests/results.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Kubernetes (or other environment)
      run: |
        echo "Deployment steps go here"
        # Add your deployment script or commands here
